### ISSUE TITLE
[OoB 5.13] Improved steps in Run the example section in README.md

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-os-example-kvstore#28]
Hi, this issue is related to Mbed OS 5.13 OoB campaign.

In the current steps, run the program first by pushing the reset button, then connect serial port. With this order, user would miss the messages from serial port.

I suggest connecting serial port first, then run the program by pushing the reset button.

**Comment by ciarmcom** [comment]
@coisme thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@coisme it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@coisme it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by coisme** [comment]
Close as OoB campaign done long time ago...
